Repository sonic-net/DASH, pull requests merged in 2024-05, with the labels that each got.

#564 [dash-p4] Support SAI API generation for bulk sync API, flow reconcile API and related counter.
  dash-pipeline/SAI/sai_api_gen.py
  dash-pipeline/SAI/templates/saiapi.h.j2
  dash-pipeline/bmv2/stages/ha.p4
Labels: Ready to merge?

#563 [doc] Include drop counters in HA API.
  documentation/high-avail/ha-api-hld.md
Labels: documentation: in review

#566 [dash-sai] Fix buffer and dtel
  dash-pipeline/SAI/src/sai_dash_buffer.cpp
  dash-pipeline/SAI/src/sai_dash_dtel.cpp
  dash-pipeline/SAI/templates/saifixedapis.cpp.j2
  dash-pipeline/SAI/templates/saiimpl.h.j2
  dash-pipeline/tests/libsai/vnet_out/vnet_out.cpp
Labels: Ready to merge?

#572 [sai-gen] Rename SAI generator SAI* objects to DashP4* objects.
  dash-pipeline/SAI/sai_api_gen.py
  dash-pipeline/SAI/utils/dash_p4/__init__.py
  dash-pipeline/SAI/utils/dash_p4/common.py
  dash-pipeline/SAI/utils/dash_p4/dash_p4_counter.py
  dash-pipeline/SAI/utils/dash_p4/dash_p4_enum.py
  dash-pipeline/SAI/utils/dash_p4/dash_p4_enum_member.py
  dash-pipeline/SAI/utils/dash_p4/dash_p4_table.py
  dash-pipeline/SAI/utils/dash_p4/dash_p4_table_action.py
  dash-pipeline/SAI/utils/dash_p4/dash_p4_table_action_param.py
  dash-pipeline/SAI/utils/dash_p4/dash_p4_table_attribute.py
  dash-pipeline/SAI/utils/dash_p4/dash_p4_table_group.py
  dash-pipeline/SAI/utils/dash_p4/dash_p4_table_key.py
  dash-pipeline/SAI/utils/dash_p4/dash_sai_extensions.py
  dash-pipeline/SAI/utils/dash_p4/sai_type_info.py
  dash-pipeline/SAI/utils/dash_p4/sai_type_solver.py
  dash-pipeline/SAI/utils/sai_gen/sai_generator.py
Labels: Ready to merge?

#553 [dash-p4] Add support to generate flow resimulation APIs
  dash-pipeline/SAI/sai_api_gen.py
  dash-pipeline/SAI/templates/saienums.j2
  dash-pipeline/SAI/utils/dash_p4/dash_p4_enum.py
  dash-pipeline/SAI/utils/dash_p4/dash_p4_enum_member.py
  dash-pipeline/bmv2/dash_counters.p4
  dash-pipeline/bmv2/dash_metadata.p4
  dash-pipeline/bmv2/dash_pipeline.p4
  dash-pipeline/bmv2/dash_routing_types.p4
  dash-pipeline/tests/libsai/vnet_out/vnet_out.cpp
  dash-pipeline/tests/saithrift/pytest/vnet/test_saithrift_vnet.py
  test/test-cases/functional/ptf/sai_dash_utils.py
  test/test-cases/functional/ptf/saidashacl.py
  test/test-cases/functional/ptf/saidashvnet_sanity.py
  test/test-cases/functional/saic/config_bidir_setup_commands.py
  test/test-cases/functional/saic/config_inbound_setup_commands.py
  test/test-cases/functional/saic/config_outbound_setup_commands.json
  test/test-cases/functional/saic/sai-api/test_sai_api_vnet_eni.py
  test/test-cases/functional/saic/sai-api/test_sai_api_vnet_in_route.py
  test/test-cases/functional/saic/sai-api/test_sai_api_vnet_out_route.py
  test/test-cases/functional/saic/tutorial/test_sai_vnet_outbound_small_scale_config_via_dpugen.py
  test/test-cases/functional/saic/tutorial/test_sai_vnet_outbound_small_scale_config_via_dpugen_create.json
  test/test-cases/scale/saic/test_sai_vnet_outbound_scale.py
  test/test-cases/scale/saic/vnet_inbound_setup_commands.json
  test/test-cases/scale/saic/vnet_outbound_setup_commands_scale.json
  test/test-cases/scale/saic/vnet_outbound_setup_commands_simple.json
  test/test-cases/scale/saic/vnet_route_setup_commands_bidirectional.json
  test/test-cases/scale/saic/vnet_route_setup_commands_unidirectional.json
Labels: documentation: in review

#573 [sai-gen] Create SAI spec for SAI API generation.
  dash-pipeline/Makefile
  dash-pipeline/SAI/Makefile
  dash-pipeline/SAI/sai_api_gen.py
  dash-pipeline/SAI/specs/dash_acl.yaml
  dash-pipeline/SAI/specs/dash_direction_lookup.yaml
  dash-pipeline/SAI/specs/dash_eni.yaml
  dash-pipeline/SAI/specs/dash_ha.yaml
  dash-pipeline/SAI/specs/dash_inbound_routing.yaml
  dash-pipeline/SAI/specs/dash_meter.yaml
  dash-pipeline/SAI/specs/dash_outbound_ca_to_pa.yaml
  dash-pipeline/SAI/specs/dash_outbound_routing.yaml
  dash-pipeline/SAI/specs/dash_pa_validation.yaml
  dash-pipeline/SAI/specs/dash_vip.yaml
  dash-pipeline/SAI/specs/dash_vnet.yaml
  dash-pipeline/SAI/specs/route.yaml
  dash-pipeline/SAI/specs/sai_spec.yaml
  dash-pipeline/SAI/templates/saiapi.h.j2
  dash-pipeline/SAI/templates/saienums.j2
  dash-pipeline/SAI/utils/dash_p4/dash_p4_counter.py
  dash-pipeline/SAI/utils/dash_p4/dash_p4_enum.py
  dash-pipeline/SAI/utils/dash_p4/dash_p4_enum_member.py
  dash-pipeline/SAI/utils/dash_p4/dash_p4_table.py
  dash-pipeline/SAI/utils/dash_p4/dash_p4_table_attribute.py
  dash-pipeline/SAI/utils/dash_p4/dash_p4_table_group.py
  dash-pipeline/SAI/utils/dash_p4/dash_p4_table_key.py
  dash-pipeline/SAI/utils/dash_p4/dash_sai_extensions.py
  dash-pipeline/SAI/utils/sai_spec/__init__.py
  dash-pipeline/SAI/utils/sai_spec/sai_api.py
  dash-pipeline/SAI/utils/sai_spec/sai_api_extension.py
  dash-pipeline/SAI/utils/sai_spec/sai_api_group.py
  dash-pipeline/SAI/utils/sai_spec/sai_attribute.py
  dash-pipeline/SAI/utils/sai_spec/sai_common.py
  dash-pipeline/SAI/utils/sai_spec/sai_enum.py
  dash-pipeline/SAI/utils/sai_spec/sai_enum_member.py
  dash-pipeline/SAI/utils/sai_spec/sai_spec.py
  dash-pipeline/SAI/utils/sai_spec/sai_struct.py
  dash-pipeline/SAI/utils/sai_spec/sai_struct_entry.py
  dash-pipeline/dockerfiles/Dockerfile.saithrift-bldr
Labels: engineering
